// Generated by gencpp from file asctec_hl_comm/mav_rcdata.msg
// DO NOT EDIT!


#ifndef ASCTEC_HL_COMM_MESSAGE_MAV_RCDATA_H
#define ASCTEC_HL_COMM_MESSAGE_MAV_RCDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace asctec_hl_comm
{
template <class ContainerAllocator>
struct mav_rcdata_
{
  typedef mav_rcdata_<ContainerAllocator> Type;

  mav_rcdata_()
    : header()
    , channel()  {
      channel.assign(0);
  }
  mav_rcdata_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , channel()  {
  (void)_alloc;
      channel.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<uint16_t, 8>  _channel_type;
  _channel_type channel;





  typedef boost::shared_ptr< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> const> ConstPtr;

}; // struct mav_rcdata_

typedef ::asctec_hl_comm::mav_rcdata_<std::allocator<void> > mav_rcdata;

typedef boost::shared_ptr< ::asctec_hl_comm::mav_rcdata > mav_rcdataPtr;
typedef boost::shared_ptr< ::asctec_hl_comm::mav_rcdata const> mav_rcdataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::asctec_hl_comm::mav_rcdata_<ContainerAllocator1> & lhs, const ::asctec_hl_comm::mav_rcdata_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.channel == rhs.channel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::asctec_hl_comm::mav_rcdata_<ContainerAllocator1> & lhs, const ::asctec_hl_comm::mav_rcdata_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace asctec_hl_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2511326b0deceba64dcfc173bba8678e";
  }

  static const char* value(const ::asctec_hl_comm::mav_rcdata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2511326b0deceba6ULL;
  static const uint64_t static_value2 = 0x4dcfc173bba8678eULL;
};

template<class ContainerAllocator>
struct DataType< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asctec_hl_comm/mav_rcdata";
  }

  static const char* value(const ::asctec_hl_comm::mav_rcdata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint16[8] channel\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::asctec_hl_comm::mav_rcdata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.channel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mav_rcdata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asctec_hl_comm::mav_rcdata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asctec_hl_comm::mav_rcdata_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "channel[]" << std::endl;
    for (size_t i = 0; i < v.channel.size(); ++i)
    {
      s << indent << "  channel[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.channel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASCTEC_HL_COMM_MESSAGE_MAV_RCDATA_H
