// Generated by gencpp from file asctec_hl_comm/Wgs84ToEnuResponse.msg
// DO NOT EDIT!


#ifndef ASCTEC_HL_COMM_MESSAGE_WGS84TOENURESPONSE_H
#define ASCTEC_HL_COMM_MESSAGE_WGS84TOENURESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asctec_hl_comm
{
template <class ContainerAllocator>
struct Wgs84ToEnuResponse_
{
  typedef Wgs84ToEnuResponse_<ContainerAllocator> Type;

  Wgs84ToEnuResponse_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  Wgs84ToEnuResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Wgs84ToEnuResponse_

typedef ::asctec_hl_comm::Wgs84ToEnuResponse_<std::allocator<void> > Wgs84ToEnuResponse;

typedef boost::shared_ptr< ::asctec_hl_comm::Wgs84ToEnuResponse > Wgs84ToEnuResponsePtr;
typedef boost::shared_ptr< ::asctec_hl_comm::Wgs84ToEnuResponse const> Wgs84ToEnuResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator1> & lhs, const ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator1> & lhs, const ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace asctec_hl_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asctec_hl_comm/Wgs84ToEnuResponse";
  }

  static const char* value(const ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Wgs84ToEnuResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asctec_hl_comm::Wgs84ToEnuResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASCTEC_HL_COMM_MESSAGE_WGS84TOENURESPONSE_H
